[general]
live_config_reload = true

[window]
padding = { x = 5, y = 15 }
decorations = "buttonless"
opacity = 0.9
blur = true

[colors.primary]
background = "#111111"

[colors]
footer_bar = { background = "#181818", foreground = "#d8d8d8" }

[font]
normal = { family = "BlexMono Nerd Font" }
size = 16

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Insert", action = "ToggleViMode" },
  { key = "Escape", mode = "Vi", action = "ToggleViMode" },
  { key = "+", mods = "Command|Shift", action = "IncreaseFontSize" },
  { key = "_", mods = "Command|Shift", action = "DecreaseFontSize" },
]
