window_padding_width 5

font_family family="BlexMono Nerd Font Mono"
font_size 14.0

background_opacity 0.92
background #0c0c0c

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{tab.active_wd.split('/')[-1]}:{tab.active_exe}"

map ctrl+cmd+, load_config_file

map cmd+shift+equal change_font_size all +2.0
map cmd+shift+minus change_font_size all -2.0
map cmd+0 change_font_size all 0

map super+t new_tab
map super+w close_tab
