background {
    monitor =
    path = ~/.local/wallpapers/jonatan-pie-3l3RwQdHRHg-unsplash.jpg
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
  hide_cursor = false
}

label {
  monitor =
  text = cmd[] ~/.local/bin/debel-logo.sh
  text_align = left
  font_family = BlexMono Nerd Font Mono
  font_size = 32
  position = 0, -200
  halign = center
  valign = top
}

input-field {
    monitor =
    size = 500, 120
    outline_thickness = 2
    outer_color = rgba(255, 255, 255, 1.0)
    dots_spacing = 0.35
    dots_center = true
    dots_text_format = 
    font_family = BlexMono Nerd Font Mono
    font_color = rgba(255, 255, 255, 1.0)
    # font_size = 40
    fade_on_empty = false
    position = 0, -250
    rounding = 10
    inner_color = rgba(255, 255, 255, 0.1)
    placeholder_text =  󰡟 󰒋  
    fail_text =     

    halign = center
    valign = center
  }
